spring:
  application:
    name: "crediya-ms-loan-applications"
  config:
    import: "optional:classpath:local.properties"
  devtools:
    add-properties: false
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"
server:
  port: "${PORT:8080}"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
